blank_issues_enabled: false
contact_links:
  - name: GigaChat support
    url: https://help.gigachat.com/
    about: |
      Please only file issues here that you believe represent actual bugs or feature requests for the GigaChat Node library.
      If you're having general trouble with the GigaChat API, please visit our help center to get support.
